name: Build executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version

      - name: Install pyinstaller
        run: |
          python -m pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile main.py
