name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmtdev-dev xvfb
      
      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1024x768x24 &

      - name: Set up environment
        run: export DISPLAY=:99
      
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile your_script.py
